<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shritik_Sharma" failures="2" tests="4" name="Login Test " time="17.706" errors="0" timestamp="2025-05-14T00:46:27 IST">
  <testcase classname="automationPractice.base.LoginTestCase" name="RegisterUser" time="1.084"/>
  <testcase classname="automationPractice.base.LoginTestCase" name="signUp" time="1.723"/>
  <testcase classname="automationPractice.base.LoginTestCase" name="createAccountForm" time="0.785">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at automationPractice.base.LoginTestCase.selectDropDownByValue(LoginTestCase.java:137)
at automationPractice.base.LoginTestCase.createAccountForm(LoginTestCase.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- createAccountForm -->
  <testcase classname="automationPractice.base.LoginTestCase" name="RegisterUserWithExistingEmail" time="4.744">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Message not showing!! expected [Email Address already exist!] but found [First name *]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Message not showing!! expected [Email Address already exist!] but found [First name *]
at automationPractice.base.LoginTestCase.RegisterUserWithExistingEmail(LoginTestCase.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- RegisterUserWithExistingEmail -->
</testsuite> <!-- Login Test  -->
